### ISSUE TITLE
時間のかかるルールがある場合にプログレスバーを表示したい

### ISSUE THREAD

**Issue by Kozu-vr** [VitDeck/VitDeck#111]
実行時に待ち時間が発生する場合に備え、プログレスバーを追加したい。

@sokuhatiku よりアイデア
try~finallyで囲んで消し忘れのないようにしないと操作不能になるが、置くだけならEditorUtility.DisplayProgressBar()で作成できる。

**Comment by Kozu-vr** [comment]
こちら、かなりの量のあるVケットのルールチェックでも待ち時間はほぼ発生しなかったため1.0.0での実装は見送ります。

**Comment by esperecyan** [comment]
@sokuhatiku 必要時に適宜プログレスバーは追加しているので、こちらはCloseで良いと思います
