### ISSUE TITLE
各種GUIを切り出してパーツとして利用できるようにしたい

### ISSUE THREAD

**Issue by sokuhatiku** [VitDeck/VitDeck#147]
思いつきです。

VketToolsとしての拡張を眺めていて思ったのですが、例えば**Validatorのログ部分だけ別のGUI上に埋め込めるようにしたら**（そして埋め込み先のGUI上からパラメータを指定してValidationの実行ができるようにしたら）、主催者側が拡張しやすそうかな？と感じました。

![image](https://user-images.githubusercontent.com/7193342/61170201-5b805c00-a5a0-11e9-8081-dfc5558b1ca4.png)

**Comment by Kozu-vr** [comment]
こちら 次回バージョンで #21 の構成変更と同時進行で行うことにします。

**Comment by esperecyan** [comment]
@sokuhatiku 必要があったときに切り出せばいいので、wontfixで良いかなと思います
