### ISSUE TITLE
エクスポートするunitypackageのファイル名にユーザーIDなどを含めたい

### ISSUE THREAD

**Issue by Kozu-vr** [VitDeck/VitDeck#173]
現時点でunitypackageのファイル名に動的な値を入れるのはSHA-1文字列以外未対応。
今後のバージョンでユーザーID、出力日付などを`{xxx}`フォーマットで指定できるようにしたい。

**Comment by Kozu-vr** [comment]
ベースフォルダ名をそのままファイル名にするオプションがあってもいいかも。

**Comment by esperecyan** [comment]
@sokuhatiku こちら実装済みです
https://github.com/VitDeck/VitDeck/blob/master/Assets/VitDeck/Exporter/ExportSetting.cs#L14
