### ISSUE TITLE
Unity 2018.4対応

### ISSUE THREAD

**Issue by Kozu-vr** [VitDeck/VitDeck#184]
Unity 2018.4に対応する。
2017についてはサポートを打ち切る方針で検討中。

現時点で判明している修正必要箇所は以下です。
- obsoluteになったPrefab周りの処理の変更
- Lighting dataなどunityバージョン依存のテスト用アセットの更新
- 不必要なasmdefファイルの削除

**Comment by sokuhatiku** [comment]
> Unity 2018.4.20f1 で VitDeck のテンプレート生成が使えなくなった件、フォルダに対して AssetDatabase.MoveAsset() を実行したあとに AssetDatabase.Refresh() を実行しないと反映されなくなったからでした
https://twitter.com/esperecyan/status/1246593318311452672?s=20
