### ISSUE TITLE
出展者IDオブジェクト外にブースが構築されている場合等、チェックを突破して入稿できてしまう場合がある

### ISSUE THREAD

**Issue by mizunanana** [VitDeck/VitDeck#203]
- 出展者IDオブジェクト外にReferencedObject以外がある場合はエラーにする
- ReferencedObject内に出展者が配置したオブジェクトがある場合はエラーにするか、テストビルド時にオフにする(テストビルドで見えているオブジェクトが入稿すると消えてしまうのを防ぐ)
- MeshBaker等を使用してエラーになるケースにも対応できる

**Comment by esperecyan** [comment]
@sokuhatiku こちら、以下に依ってresolveで良いと思います
> マルチシーンで余計なシーンが開かれているかの検出、及びシーン直下に入稿オブジェクトとReferenceObject以外のオブジェクトが配置されているかどうかの検証ロジックを 5d80e7cec849e79bad915fc909e697fe9c6bd6b2 で作成しました。
